name: DevSecOps Pipeline for OWASP Juice Shop on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker on Windows
        run: |
          Start-Service docker
          docker --version

      - name: Build Juice Shop Docker Image
        run: docker build -t juice-shop:latest .

  sast:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Semgrep for SAST
        shell: bash
        run: |
          pip install semgrep
          semgrep --config p/security-audit --output semgrep.sarif

      - name: Upload Semgrep Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif

  sca:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install OWASP Dependency-Check
        run: |
          curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v7.0.4/dependency-check-7.0.4-release.zip
          Expand-Archive -Path dependency-check-7.0.4-release.zip -DestinationPath dependency-check

      - name: Run OWASP Dependency-Check for SCA
        run: |
          dependency-check\bin\dependency-check.bat --scan . --format HTML --out dependency-check-report.html

      - name: U
